### PR TITLE
cold slice eos

### PR DESCRIPTION
**Pull request by Max-Jacobi**

### CODE REVIEW

**Comment by jfields7** [comment]
A couple things I caught while going through the review:
1. You can abbreviate the new headers by inheriting from `EOSPolicyInterface`. It defines no functions, but it automatically provides things like `n_species`, `mb`, etc. If you don't want to do this to avoid adding things like `min_T` and `max_T` to the class namespace, I strongly suggest making a new interface, `ColdEOSPolicyInterface`, that performs a similar role. This way when new cold EOS classes inevitably get added in the future, there's an easy way to include all the necessary variables right off the bat.
2. I recommend renaming `cold_idealgas.*` to `cold_polytrope.*`.

Other than that, everything looks fine.

**Review by jfields7 — CHANGES_REQUESTED** [review]
A couple things I caught while going through the review:
1. You can abbreviate the new headers by inheriting from EOSPolicyInterface. It defines no functions, but it automatically provides things like n_species, mb, etc. If you don't want to do this to avoid adding things like min_T and max_T to the class namespace, I strongly suggest making a new interface, ColdEOSPolicyInterface, that performs a similar role. This way when new cold EOS classes inevitably get added in the future, there's an easy way to include all the necessary variables right off the bat.
2. I recommend renaming cold_idealgas.* to cold_polytrope.*.

Other than that, everything looks fine.

**Comment by Max-Jacobi** [comment]
I added the interface. I kept it out initially because I planned to inherit directly from the hot counterparts but ended up only doing this in the pwp.

**Review by jfields7 — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
